# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api_scanner.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x61pi_scanner.proto\x12\'com.coderalliance.apimaster.service.rpc\"M\n\x0eScanApiRequest\x12\x12\n\nproject_id\x18\x01 \x01(\x03\x12\x13\n\x0bgit_address\x18\x02 \x01(\t\x12\x12\n\ngit_branch\x18\x03 \x01(\t\"3\n\x0fScanApiResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\x8b\x01\n\x0eScanApiService\x12y\n\x04Scan\x12\x37.com.coderalliance.apimaster.service.rpc.ScanApiRequest\x1a\x38.com.coderalliance.apimaster.service.rpc.ScanApiResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api_scanner_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SCANAPIREQUEST']._serialized_start=62
  _globals['_SCANAPIREQUEST']._serialized_end=139
  _globals['_SCANAPIRESPONSE']._serialized_start=141
  _globals['_SCANAPIRESPONSE']._serialized_end=192
  _globals['_SCANAPISERVICE']._serialized_start=195
  _globals['_SCANAPISERVICE']._serialized_end=334
# @@protoc_insertion_point(module_scope)
